/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ICliConfig {
  ethereum: {
    /**
     * Network endpoint URL
     */
    endpoint: string;
    /**
     * Directory where contract deployment lock files stored
     */
    lockfilesDir: string;
    /**
     * Network from address
     */
    from: string;
    /**
     * Default Gas limit
     */
    gas: string;
    /**
     * Default Gas price
     */
    gasPrice: string;
    /**
     * SNPC token contract
     */
    SNPCToken: {
      /**
       * Path to the contract schema
       */
      schema: string;
      totalSupplyTokens: string;
      reservedTeamTokens: string;
      reservedBountyTokens: string;
      reservedReserveTokens: string;
      reservedPartnersTokens: string;
      [k: string]: any;
    };
    /**
     * SNPC token pre-ico contract
     */
    SNPCPreICO: {
      /**
       * Path to the contract schema
       */
      schema: string;
      /**
       * Team wallet address on network
       */
      teamWallet: string;
      lowCapTokens: string;
      hardCapTokens: string;
      lowCapTxWei: string;
      hardCapTxWei: string;
      [k: string]: any;
    };
    /**
     * SNPC token ico contract
     */
    SNPCICOStage1?: {
      /**
       * Path to the contract schema
       */
      schema: string;
      /**
       * Team wallet address on network
       */
      teamWallet: string;
      lowCapTokens: string;
      hardCapTokens: string;
      lowCapTxWei: string;
      hardCapTxWei: string;
      [k: string]: any;
    };
    /**
     * SNPC token ico contract
     */
    SNPCICOStage2?: {
      /**
       * Path to the contract schema
       */
      schema: string;
      /**
       * Team wallet address on network
       */
      teamWallet: string;
      lowCapTokens: string;
      hardCapTokens: string;
      lowCapTxWei: string;
      hardCapTxWei: string;
      [k: string]: any;
    };
    /**
     * SNPC token ico contract
     */
    SNPCICOStage3?: {
      /**
       * Path to the contract schema
       */
      schema: string;
      /**
       * Team wallet address on network
       */
      teamWallet: string;
      lowCapTokens: string;
      hardCapTokens: string;
      lowCapTxWei: string;
      hardCapTxWei: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  [k: string]: any;
}
